server:
  port: 8888



myapp:
  api-prefix: /api

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://127.0.0.1:8080
          predicates:
            - Path=${myapp.api-prefix}/identity/**
          filters:
            - StripPrefix=1

        - id: student_service
          uri: http://127.0.0.1:8081
          predicates:
            - Path= ${myapp.api-prefix}/student/**
          filters:
            - StripPrefix=1


        - id: course_service
          uri: http://127.0.0.1:8082
          predicates:
            - Path= ${myapp.api-prefix}/elasticSearch/**
          filters:
            - StripPrefix=1



