server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: "jdbc:mysql://localhost:3306/edu_database"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 22012003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 10800 # in second
  refreshable-duration: 36000 # in seconds

#app:
#  services:
#    profile: http://localhost:8081/profile