server:
  port: 8081
  servlet:
    context-path: /student
spring:
  application:
    name: student-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: tien22012003