server:
  port: 8081
  servlet:
    context-path: /student
spring:
  application:
    name: student-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: tien22012003

  mail:
    host: smtp.gmail.com
    port: 587
    username: chauduongphattien2201@gmail.com
    password: qwxf nsem tfgu ekzw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true




token:
  name: tokenClient
  host: localhost:3001


jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"