server:
  port: 8082
  servlet:
    context-path: /elasticSearch

DATA_HOST: ${ELASTICSEARCH_HOST:localhost}
DATA_PORT: ${ELASTICSEARCH_PORT:9200}
IDENTITY_HOST: ${IDENTITY_URL:http://127.0.0.1:8080}
spring:

  application:
    name: elasticSearch-server
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchAutoConfiguration
  data:
    elasticsearch:
      cluster-nodes: localhost:9100
      repositories:
        enabled: true

logging:
  level:
    org.springframework.data.elasticsearch: DEBUG
    org.elasticsearch.client: DEBUG