server:
  port: 8082
  servlet:
    context-path: /elasticSearch


spring:

  application:
    name: elasticSearch-server
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchAutoConfiguration
  data:
    elasticsearch:
      cluster-nodes: localhost:9100
      repositories:
        enabled: true

logging:
  level:
    org.springframework.data.elasticsearch: DEBUG
    org.elasticsearch.client: DEBUG